project_id = "aqpkkdhkbklhmjjiicsn"

[functions.fetch-ge-matches]
verify_jwt = true

[functions.sync-match-results]
verify_jwt = true

[functions.get-match-crests]
verify_jwt = true

[functions.check-cpf-exists]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.verify-whatsapp-otp]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.update-football-winners]
verify_jwt = true
